services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: nuxt
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/server/data:/app/dist/data
    environment:
      - HOST=0.0.0.0
      - NUXT_APP_GOOGLE_CLIENT_ID=${NUXT_APP_GOOGLE_CLIENT_ID}
      - NUXT_APP_DRF_CLIENT_ID=${NUXT_APP_DRF_CLIENT_ID}
      - NUXT_APP_DRF_CLIENT_SECRET=${NUXT_APP_DRF_CLIENT_SECRET}
      - NUXT_ENCRYPTION_KEY=${NUXT_ENCRYPTION_KEY}
      - NUXT_CLIENT_SIDE_URL=${NUXT_CLIENT_SIDE_URL}
      - NUXT_SERVER_SIDE_URL=${NUXT_SERVER_SIDE_URL}
      - NUXT_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: django
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=${SOCIAL_AUTH_GOOGLE_OAUTH2_KEY}
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=${SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET}
      - EMAIL_BACKEND=${EMAIL_BACKEND}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - GET_SCORES_EMAILS=${GET_SCORES_EMAILS}
      - TO_SEND_EMAILS=${TO_SEND_EMAILS}
      - API_KEY=${API_KEY}
      - AI_MODEL=${AI_MODEL}
      - SITE_URL=${SITE_URL}
      - ALLOWED_EMAIL_DOMAIN=${ALLOWED_EMAIL_DOMAIN}
      - PYTHONIOENCODING=utf-8
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  analyze-tool:
    build:
      context: ./analyzeTool
      dockerfile: Dockerfile
    container_name: analyze-tool
    ports:
      - "8501:8501"
    volumes:
      - ./analyzeTool:/app
    environment:
      - WATCHDOG_TIMEOUT=10
      - PYTHONPATH=/app/src
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    command: streamlit run src/main.py --server.runOnSave=true
    depends_on:
      - db
    tty: true

volumes:
  postgres_data:
