# Generated by Django 5.1.7 on 2025-11-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpair',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
