# Generated by Django 5.1.5 on 2025-11-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_generation", "0002_alter_textpair_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnglishText",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(help_text="生成された英語文章")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "english_texts",
                "ordering": ["-created_at"],
            },
        ),
    ]
