# Generated by Django 5.1.5 on 2025-11-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_generation", "0003_englishtext"),
    ]

    operations = [
        migrations.AddField(
            model_name="englishtext",
            name="is_translated",
            field=models.BooleanField(default=False, help_text="翻訳済みかどうか"),
        ),
        migrations.AddField(
            model_name="englishtext",
            name="meaning",
            field=models.TextField(blank=True, default="", help_text="英語文章の和訳"),
        ),
    ]
